import logo512 from "../assets/img/logo512.png";
import icon from "../assets/img/reindiaskill-icon.png";
import user_placeholder from "../assets/img/Portrait_Placeholder.png";
import file_image from "../assets/img/file-placeholder.jpg";
import camera_placeholder from "../assets/img/camera-placeholder.png";
import noitem from "../assets/img/no-record-found.png";
import cross_img_png from "../assets/img/img-not-found.png";
import help_support from "../assets/img/help_support.png";
import survey_bg_page from "../assets/img/survey-bg.webp";
export const  logo = logo512;
export const  filePlaceholder = file_image;
export const  userplaceholder = user_placeholder;
export const  cameraPlaceholder = camera_placeholder;
export const  norecordfound = noitem;
export const  icon_fornt = icon;
export const  cross_img = cross_img_png;
export const  help_and_support = help_support;
export const  survey_bg = survey_bg_page;
